name: Build APK with ECH Support
on:
  push:
    branches: [ech-support]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo first-step-before-checkout
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: false
          ref: ech-support
      - run: echo done
